# Generated by Django 5.2.1 on 2025-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
