# Generated by Django 5.2.1 on 2025-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('photo', models.TextField(blank=True, null=True)),
                ('student_class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('roll_number', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_relation', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
